general:
  description: "Unjacketed test"
  tags: ""
  run_dir: ""
  run_id: ""

mesh:
  Re: 1.0
  H: 0.01 
  N: 6             # fallback only
  Nr: 30            # quasi-1D: minimal elements in r
  Nz: 30          # many layers in z
  grade_r: true   # uniform in r
  grade_z_bottom: false  # refine near z=H/2 (top face, drainage boundary)

materials:
  E: 1.44e10
  nu: 0.2
  alpha: 0.78
  perm: 1.0e-20
  visc: 1.0e-3
  M: 1.35e10

    #UNJACKETED
boundary_conditions:
  top: # z=0
    sig_zz: -1.0e5
    Pressure: 0.0
    U_z_rigid: 1
    U_r: 0.0

  bottom:
    U_z: 0.0
  
  right:
    Pressure: 0.0
  
  left:
    U_r: 0.0

numerical:
  num_steps: 1000
  theta_cn: 0.75

output:
  results: "outputs/results.bp"
  timeseries: "outputs/fem_timeseries.nc"
